//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profitocracy.Mobile.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Profitocracy.Mobile.Resources.Strings.AppResources_ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Setup_FirstProfile {
            get {
                return ResourceManager.GetString("Setup_FirstProfile", resourceCulture);
            }
        }
        
        internal static string Pages_Home {
            get {
                return ResourceManager.GetString("Pages_Home", resourceCulture);
            }
        }
        
        internal static string Home_Balance {
            get {
                return ResourceManager.GetString("Home_Balance", resourceCulture);
            }
        }
        
        internal static string Home_DailyAmounts {
            get {
                return ResourceManager.GetString("Home_DailyAmounts", resourceCulture);
            }
        }
        
        internal static string Home_TodayBalance {
            get {
                return ResourceManager.GetString("Home_TodayBalance", resourceCulture);
            }
        }
        
        internal static string Home_TomorrowBalance {
            get {
                return ResourceManager.GetString("Home_TomorrowBalance", resourceCulture);
            }
        }
        
        internal static string Home_SpendingTypes {
            get {
                return ResourceManager.GetString("Home_SpendingTypes", resourceCulture);
            }
        }
        
        internal static string Settings_Categories {
            get {
                return ResourceManager.GetString("Settings_Categories", resourceCulture);
            }
        }
        
        internal static string Home_Main {
            get {
                return ResourceManager.GetString("Home_Main", resourceCulture);
            }
        }
        
        internal static string Home_Saved {
            get {
                return ResourceManager.GetString("Home_Saved", resourceCulture);
            }
        }
        
        internal static string Home_Secondary {
            get {
                return ResourceManager.GetString("Home_Secondary", resourceCulture);
            }
        }
        
        internal static string Home_NoCategories {
            get {
                return ResourceManager.GetString("Home_NoCategories", resourceCulture);
            }
        }
        
        internal static string Home_SavedBalance {
            get {
                return ResourceManager.GetString("Home_SavedBalance", resourceCulture);
            }
        }
        
        internal static string Setup_GoToExpenses {
            get {
                return ResourceManager.GetString("Setup_GoToExpenses", resourceCulture);
            }
        }
        
        internal static string Setup_InitialBalance {
            get {
                return ResourceManager.GetString("Setup_InitialBalance", resourceCulture);
            }
        }
        
        internal static string Setup_ProfileName {
            get {
                return ResourceManager.GetString("Setup_ProfileName", resourceCulture);
            }
        }
        
        internal static string Pages_Transactions {
            get {
                return ResourceManager.GetString("Pages_Transactions", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Income {
            get {
                return ResourceManager.GetString("AddTransaction_Income", resourceCulture);
            }
        }
        
        internal static string Pages_Settings {
            get {
                return ResourceManager.GetString("Pages_Settings", resourceCulture);
            }
        }
        
        internal static string Pages_NewTransaction {
            get {
                return ResourceManager.GetString("Pages_NewTransaction", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Amount {
            get {
                return ResourceManager.GetString("AddTransaction_Amount", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Category {
            get {
                return ResourceManager.GetString("AddTransaction_Category", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Date {
            get {
                return ResourceManager.GetString("AddTransaction_Date", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Description {
            get {
                return ResourceManager.GetString("AddTransaction_Description", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Expense {
            get {
                return ResourceManager.GetString("AddTransaction_Expense", resourceCulture);
            }
        }
        
        internal static string AddTransaction_SaveTransaction {
            get {
                return ResourceManager.GetString("AddTransaction_SaveTransaction", resourceCulture);
            }
        }
        
        internal static string Settings_Application {
            get {
                return ResourceManager.GetString("Settings_Application", resourceCulture);
            }
        }
        
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        internal static string Settings_Profiles {
            get {
                return ResourceManager.GetString("Settings_Profiles", resourceCulture);
            }
        }
        
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        internal static string Pages_NewCategory {
            get {
                return ResourceManager.GetString("Pages_NewCategory", resourceCulture);
            }
        }
        
        internal static string AddCategory_CategoryName {
            get {
                return ResourceManager.GetString("AddCategory_CategoryName", resourceCulture);
            }
        }
        
        internal static string Categories_NoLimits {
            get {
                return ResourceManager.GetString("Categories_NoLimits", resourceCulture);
            }
        }
        
        internal static string AddCategory_PlannedAmount {
            get {
                return ResourceManager.GetString("AddCategory_PlannedAmount", resourceCulture);
            }
        }
        
        internal static string AddCategory_SaveCategory {
            get {
                return ResourceManager.GetString("AddCategory_SaveCategory", resourceCulture);
            }
        }
        
        internal static string AddCategory_SpecifyPlannedAmount {
            get {
                return ResourceManager.GetString("AddCategory_SpecifyPlannedAmount", resourceCulture);
            }
        }
        
        internal static string Transactions_DateRange {
            get {
                return ResourceManager.GetString("Transactions_DateRange", resourceCulture);
            }
        }
        
        internal static string ThemeSettings_LightTheme {
            get {
                return ResourceManager.GetString("ThemeSettings_LightTheme", resourceCulture);
            }
        }
        
        internal static string ThemeSettings_Dark {
            get {
                return ResourceManager.GetString("ThemeSettings_Dark", resourceCulture);
            }
        }
        
        internal static string ThemeSettings_System {
            get {
                return ResourceManager.GetString("ThemeSettings_System", resourceCulture);
            }
        }
        
        internal static string Languages_English {
            get {
                return ResourceManager.GetString("Languages_English", resourceCulture);
            }
        }
        
        internal static string Languages_Russian {
            get {
                return ResourceManager.GetString("Languages_Russian", resourceCulture);
            }
        }
        
        internal static string InfoAlert_ChangeLanguage_Message {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Message", resourceCulture);
            }
        }
        
        internal static string InfoAlert_ChangeLanguage_Title {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Title", resourceCulture);
            }
        }
        
        internal static string InfoAlert_ChangeLanguage_Ok {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Ok", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_Title {
            get {
                return ResourceManager.GetString("ErrorAlert_Title", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ErrorAlert_Ok", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_Description {
            get {
                return ResourceManager.GetString("ErrorAlert_Description", resourceCulture);
            }
        }
        
        internal static string CommonError_GetCategoryInfo {
            get {
                return ResourceManager.GetString("CommonError_GetCategoryInfo", resourceCulture);
            }
        }
        
        internal static string CommonError_ShowFilteredTransactions {
            get {
                return ResourceManager.GetString("CommonError_ShowFilteredTransactions", resourceCulture);
            }
        }
        
        internal static string CommonError_OpenAddCategoryPage {
            get {
                return ResourceManager.GetString("CommonError_OpenAddCategoryPage", resourceCulture);
            }
        }
        
        internal static string CommonError_OpenEditTransactionPage {
            get {
                return ResourceManager.GetString("CommonError_OpenEditTransactionPage", resourceCulture);
            }
        }
        
        internal static string CommonError_InternalErrorTryAgain {
            get {
                return ResourceManager.GetString("CommonError_InternalErrorTryAgain", resourceCulture);
            }
        }
        
        internal static string CommonError_FindTransactionToDelete {
            get {
                return ResourceManager.GetString("CommonError_FindTransactionToDelete", resourceCulture);
            }
        }
        
        internal static string CommonError_PlannedAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_PlannedAmountNumber", resourceCulture);
            }
        }
        
        internal static string CommonError_GetCurrentProfile {
            get {
                return ResourceManager.GetString("CommonError_GetCurrentProfile", resourceCulture);
            }
        }
        
        internal static string CommonError_GetSettings {
            get {
                return ResourceManager.GetString("CommonError_GetSettings", resourceCulture);
            }
        }
        
        internal static string CommonError_BalanceNumber {
            get {
                return ResourceManager.GetString("CommonError_BalanceNumber", resourceCulture);
            }
        }
        
        internal static string AddTransaction_NoneCategory {
            get {
                return ResourceManager.GetString("AddTransaction_NoneCategory", resourceCulture);
            }
        }
        
        internal static string CommonError_AmountNumber {
            get {
                return ResourceManager.GetString("CommonError_AmountNumber", resourceCulture);
            }
        }
        
        internal static string CommonError_TransactionType {
            get {
                return ResourceManager.GetString("CommonError_TransactionType", resourceCulture);
            }
        }
        
        internal static string Pages_Language {
            get {
                return ResourceManager.GetString("Pages_Language", resourceCulture);
            }
        }
        
        internal static string Pages_Categories {
            get {
                return ResourceManager.GetString("Pages_Categories", resourceCulture);
            }
        }
        
        internal static string Pages_Theme {
            get {
                return ResourceManager.GetString("Pages_Theme", resourceCulture);
            }
        }
        
        internal static string Home_Categories {
            get {
                return ResourceManager.GetString("Home_Categories", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Secondary {
            get {
                return ResourceManager.GetString("AddTransaction_Secondary", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Saved {
            get {
                return ResourceManager.GetString("AddTransaction_Saved", resourceCulture);
            }
        }
        
        internal static string AddTransaction_Main {
            get {
                return ResourceManager.GetString("AddTransaction_Main", resourceCulture);
            }
        }
        
        internal static string Transactions_Income {
            get {
                return ResourceManager.GetString("Transactions_Income", resourceCulture);
            }
        }
        
        internal static string Transactions_Main {
            get {
                return ResourceManager.GetString("Transactions_Main", resourceCulture);
            }
        }
        
        internal static string Transactions_Saved {
            get {
                return ResourceManager.GetString("Transactions_Saved", resourceCulture);
            }
        }
        
        internal static string Transactions_Secondary {
            get {
                return ResourceManager.GetString("Transactions_Secondary", resourceCulture);
            }
        }
        
        internal static string CommonError_FindTransactionToEdit {
            get {
                return ResourceManager.GetString("CommonError_FindTransactionToEdit", resourceCulture);
            }
        }
        
        internal static string InfoAlert_FeatureNotAvailable_Message {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Message", resourceCulture);
            }
        }
        
        internal static string InfoAlert_FeatureNotAvailable_Title {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Title", resourceCulture);
            }
        }
        
        internal static string InfoAlert_FeatureNotAvailable_Ok {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Ok", resourceCulture);
            }
        }
        
        internal static string CommonError_FindCategoryToDelete {
            get {
                return ResourceManager.GetString("CommonError_FindCategoryToDelete", resourceCulture);
            }
        }
    }
}
