//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profitocracy.Mobile.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Profitocracy.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateFirstProfile {
            get {
                return ResourceManager.GetString("CreateFirstProfile", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        internal static string DailyAmounts {
            get {
                return ResourceManager.GetString("DailyAmounts", resourceCulture);
            }
        }
        
        internal static string FromInitialBalance {
            get {
                return ResourceManager.GetString("FromInitialBalance", resourceCulture);
            }
        }
        
        internal static string FromActualBalance {
            get {
                return ResourceManager.GetString("FromActualBalance", resourceCulture);
            }
        }
        
        internal static string SpendingTypes {
            get {
                return ResourceManager.GetString("SpendingTypes", resourceCulture);
            }
        }
        
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        internal static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string ThereIsNoCategories {
            get {
                return ResourceManager.GetString("ThereIsNoCategories", resourceCulture);
            }
        }
        
        internal static string SavedBalance {
            get {
                return ResourceManager.GetString("SavedBalance", resourceCulture);
            }
        }
        
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        internal static string InitialBalance {
            get {
                return ResourceManager.GetString("InitialBalance", resourceCulture);
            }
        }
        
        internal static string GoToExpenses {
            get {
                return ResourceManager.GetString("GoToExpenses", resourceCulture);
            }
        }
        
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string AddNewTransaction {
            get {
                return ResourceManager.GetString("AddNewTransaction", resourceCulture);
            }
        }
        
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string SaveTransaction {
            get {
                return ResourceManager.GetString("SaveTransaction", resourceCulture);
            }
        }
        
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string NoLimits {
            get {
                return ResourceManager.GetString("NoLimits", resourceCulture);
            }
        }
        
        internal static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        internal static string SpecifyPlannedAmount {
            get {
                return ResourceManager.GetString("SpecifyPlannedAmount", resourceCulture);
            }
        }
        
        internal static string PlannedAmount {
            get {
                return ResourceManager.GetString("PlannedAmount", resourceCulture);
            }
        }
        
        internal static string SaveCategory {
            get {
                return ResourceManager.GetString("SaveCategory", resourceCulture);
            }
        }
        
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        internal static string LightThemeText {
            get {
                return ResourceManager.GetString("LightThemeText", resourceCulture);
            }
        }
        
        internal static string DarkThemeText {
            get {
                return ResourceManager.GetString("DarkThemeText", resourceCulture);
            }
        }
        
        internal static string SystemThemeText {
            get {
                return ResourceManager.GetString("SystemThemeText", resourceCulture);
            }
        }
        
        internal static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        internal static string RussianLanguage {
            get {
                return ResourceManager.GetString("RussianLanguage", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageAlertTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageAlertTitle", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageAlertMessage {
            get {
                return ResourceManager.GetString("ChangeLanguageAlertMessage", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageAlertOk {
            get {
                return ResourceManager.GetString("ChangeLanguageAlertOk", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_Title {
            get {
                return ResourceManager.GetString("ErrorAlert_Title", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ErrorAlert_Ok", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_Description {
            get {
                return ResourceManager.GetString("ErrorAlert_Description", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_GetCategoryInfo {
            get {
                return ResourceManager.GetString("ErrorAlert_GetCategoryInfo", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_ShowFilteredTransactions {
            get {
                return ResourceManager.GetString("ErrorAlert_ShowFilteredTransactions", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_OpenAddCategoryPage {
            get {
                return ResourceManager.GetString("ErrorAlert_OpenAddCategoryPage", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_OpenAddTransactionPage {
            get {
                return ResourceManager.GetString("ErrorAlert_OpenAddTransactionPage", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_InternalErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorAlert_InternalErrorTryAgain", resourceCulture);
            }
        }
        
        internal static string ErrorAlert_FindTransactionToDelete {
            get {
                return ResourceManager.GetString("ErrorAlert_FindTransactionToDelete", resourceCulture);
            }
        }
        
        internal static string CommonError_PlannedAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_PlannedAmountNumber", resourceCulture);
            }
        }
        
        internal static string CommonError_GetCurrentProfile {
            get {
                return ResourceManager.GetString("CommonError_GetCurrentProfile", resourceCulture);
            }
        }
        
        internal static string CommonError_GetSettings {
            get {
                return ResourceManager.GetString("CommonError_GetSettings", resourceCulture);
            }
        }
        
        internal static string CommonError_BalanceNumber {
            get {
                return ResourceManager.GetString("CommonError_BalanceNumber", resourceCulture);
            }
        }
        
        internal static string AddTransaction_NoneCategory {
            get {
                return ResourceManager.GetString("AddTransaction_NoneCategory", resourceCulture);
            }
        }
        
        internal static string CommonError_AmountNumber {
            get {
                return ResourceManager.GetString("CommonError_AmountNumber", resourceCulture);
            }
        }
        
        internal static string CommonError_TransactionType {
            get {
                return ResourceManager.GetString("CommonError_TransactionType", resourceCulture);
            }
        }
    }
}
